"""initial schema

Revision ID: c2d56f46d307
Revises: 
Create Date: 2026-08-23 13:02:40.385250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2d56f46d307'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.BigInteger(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('headline', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sentiment', sa.String(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('symbols', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('news_id', 'stock_id', name='uq_news_news_id_stock_id')
    )
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_news_id'), ['news_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_stock_id'), ['stock_id'], unique=False)

    op.create_table('patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('milliseconds', sa.BigInteger(), nullable=False),
    sa.Column('pattern_name', sa.String(length=150), nullable=False),
    sa.Column('sentiment', sa.String(length=150), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=150), nullable=False),
    sa.Column('latest_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'pattern_name', 'sentiment', 'timeframe', 'milliseconds', name='uq_patterns_stock_pattern_sentiment_timeframe_ms')
    )
    with op.batch_alter_table('patterns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patterns_stock_id'), ['stock_id'], unique=False)

    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_news', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_news_news_id'), ['news_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_news_stock_id'), ['stock_id'], unique=False)

    op.create_table('watchlist_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_stocks')
    with op.batch_alter_table('stock_news', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_news_stock_id'))
        batch_op.drop_index(batch_op.f('ix_stock_news_news_id'))

    op.drop_table('stock_news')
    op.drop_table('watchlists')
    with op.batch_alter_table('patterns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patterns_stock_id'))

    op.drop_table('patterns')
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_stock_id'))
        batch_op.drop_index(batch_op.f('ix_news_news_id'))

    op.drop_table('news')
    op.drop_table('users')
    op.drop_table('stocks')
    # ### end Alembic commands ###
